//! `bitflip.table(...)` 的引擎级测试：M7 交付物"自定义视图数据源"。
//!
//! 这里走的是**真实路径**（`ScriptEngine::run` → 宿主绑定 → 解析），所以能断言
//! 两件单元测试看不到的事：
//!
//! * **拒绝的措辞**。异常消息是给用户看的，它只在 JS 异常对象里 ——
//!   Rust 侧的 `Display` 是"Exception generated by JS"。用户看到的界面文案
//!   就是从这条消息来的，所以必须逐字核对它"说清楚了哪里错"。
//! * **生命周期**。表与标注一样"要么全留、要么不留"：脚本失败或中断时
//!   一张都不许剩，重跑之前必须清空。这两件事都只有在引擎层才看得见。
//!
//! 形状层面的测试（单元格转换、列类型、额度）在 `src/table.rs` 的单元测试里。

use std::time::Duration;

use bitflip_script::{
    ColumnKind, Host, Limits, ScriptEngine, TableCell, MAX_TABLES_PER_RUN, MAX_TABLE_CELLS,
};

fn engine() -> ScriptEngine {
    ScriptEngine::new(Limits {
        timeout: Duration::from_secs(5),
    })
    .expect("创建脚本引擎")
}

/// 跑一段脚本，要求它**成功**。
fn run_ok(host: &Host, source: &str) -> bitflip_script::ScriptOutcome {
    engine().run(host, source).expect("脚本应当成功")
}

/// 跑一段脚本，要求它**失败**，返回面向用户的消息。
fn run_err(host: &Host, source: &str) -> String {
    engine()
        .run(host, source)
        .expect_err("脚本应当失败")
        .to_string()
}

// ---------------------------------------------------------------------------
// 正常路径
// ---------------------------------------------------------------------------

#[test]
fn a_script_publishes_a_named_table_with_typed_columns() {
    let host = Host::new(None);
    let source = r#"
        bitflip.log('开始');
        const rows = bitflip.table(
            'memcpy 调用点',
            [
                {name: '地址', type: 'address'},
                {name: '调用者'},
                {name: '参数个数', type: 'number'},
                {name: '可能内联', type: 'bool'},
            ],
            [
                [0x140009218, 'main', 3, false],
                ['0000000000401000', 'helper', 2, true],
            ],
            {description: '按直接调用 xref 收集'}
        );
        bitflip.log('共 ' + rows + ' 行');
    "#;
    let outcome = run_ok(&host, source);
    assert_eq!(outcome.tables, 1, "应当产出一张表");
    assert_eq!(outcome.logs.len(), 2);

    // 返回值就是行数：脚本不必再数一遍（它自己也可能数错）。
    assert_eq!(outcome.logs[1].message, "共 2 行");

    let tables = host.tables();
    assert_eq!(tables.len(), 1);
    let table = &tables[0];
    assert_eq!(table.name, "memcpy 调用点");
    assert_eq!(table.description.as_deref(), Some("按直接调用 xref 收集"));
    assert_eq!(table.row_count(), 2);
    assert_eq!(table.columns[0].kind, ColumnKind::Address);
    assert_eq!(table.columns[1].kind, ColumnKind::Text);
    assert_eq!(table.columns[2].kind, ColumnKind::Number);
    assert_eq!(table.columns[3].kind, ColumnKind::Bool);
    assert_eq!(table.rows[0][0], TableCell::Address(0x0001_4000_9218));
    assert_eq!(table.rows[1][0], TableCell::Address(0x40_1000));

    // 摘要给界面轮询用，形状与全量一致但不带数据行。
    let summaries = host.table_summaries();
    assert_eq!(summaries.len(), 1);
    assert_eq!(summaries[0].row_count, 2);
    assert_eq!(summaries[0].columns, table.columns);

    // 按名字取表：端点就是这么做的。
    assert!(host.table("memcpy 调用点").is_some());
    assert!(host.table("不存在的表").is_none());
}

#[test]
fn several_tables_survive_one_run_in_the_order_the_script_made_them() {
    let host = Host::new(None);
    let outcome = run_ok(
        &host,
        r#"
        bitflip.table('第一张', ['a'], [[1]]);
        bitflip.table('第二张', ['b'], [[2]]);
        bitflip.table('第三张', ['c'], [[3]]);
        "#,
    );
    assert_eq!(outcome.tables, 3);
    let names: Vec<String> = host.tables().into_iter().map(|t| t.name).collect();
    assert_eq!(
        names,
        vec!["第一张", "第二张", "第三张"],
        "视图列表的顺序就是脚本产出的顺序"
    );
}

// ---------------------------------------------------------------------------
// 拒绝的措辞
// ---------------------------------------------------------------------------

#[test]
fn a_ragged_row_is_refused_by_naming_the_row_and_both_counts() {
    let host = Host::new(None);
    let message = run_err(
        &host,
        "bitflip.table('表', ['a', 'b'], [['x', 'y'], ['只有一格']]);",
    );
    assert!(
        message.contains("第 2 行"),
        "必须指出是第几行（1 起）：{message}"
    );
    assert!(
        message.contains('1') && message.contains('2') && message.contains("列"),
        "必须同时给出这一行有几个、以及一共几列：{message}"
    );
    assert!(
        host.tables().is_empty(),
        "被拒绝的调用不得留下任何表：{:?}",
        host.tables()
    );
}

#[test]
fn an_unknown_column_type_lists_the_valid_ones() {
    let host = Host::new(None);
    let message = run_err(
        &host,
        "bitflip.table('表', [{name: 'a', type: 'hex'}], []);",
    );
    assert!(message.contains("hex"), "要给出收到的类型：{message}");
    for valid in ColumnKind::all() {
        assert!(
            message.contains(valid),
            "可选值 {valid} 必须出现在报错里：{message}"
        );
    }
}

#[test]
fn a_non_scalar_cell_is_refused_with_the_location_and_the_reason() {
    let host = Host::new(None);
    let message = run_err(&host, "bitflip.table('表', ['a'], [[{x: 1}]]);");
    assert!(message.contains("第 1 行"), "要有位置：{message}");
    assert!(
        message.contains("标量"),
        "要说清只能是标量，而不是让脚本去猜：{message}"
    );
}

#[test]
fn an_address_beyond_the_safe_integer_range_is_refused_not_truncated() {
    let host = Host::new(None);
    let message = run_err(
        &host,
        "bitflip.table('表', [{name: '地址', type: 'address'}], [[9007199254740994]]);",
    );
    assert!(
        message.contains("安全整数") && message.contains("十六进制"),
        "超出精度必须报错并给出替代写法：{message}"
    );
}

#[test]
fn a_duplicate_table_name_is_refused_rather_than_silently_keeping_two() {
    let host = Host::new(None);
    let message = run_err(
        &host,
        r#"
        bitflip.table('清单', ['a'], [[1]]);
        bitflip.table('清单', ['a'], [[2]]);
        "#,
    );
    assert!(
        message.contains("重复"),
        "重名要说清是重名，而不是别的错：{message}"
    );
}

#[test]
fn the_table_count_limit_says_how_many_are_allowed() {
    let host = Host::new(None);
    // 循环造到超限：脚本里最可能的形态就是"每处理一类东西就建一张表"。
    let source = format!(
        "for (let i = 0; i <= {MAX_TABLES_PER_RUN}; i++) {{ bitflip.table('表' + i, ['a'], [[i]]); }}"
    );
    let message = run_err(&host, &source);
    assert!(
        message.contains(&MAX_TABLES_PER_RUN.to_string()),
        "报错要给出上限：{message}"
    );
    assert!(
        message.contains("合并"),
        "要给出下一步怎么做，而不只是拒绝：{message}"
    );
}

#[test]
fn an_oversized_table_is_refused_before_it_is_built() {
    let host = Host::new(None);
    // 上限的检查发生在逐格解析**之前**：否则脚本会先吃掉几百兆内存再被告知
    // 超限，而那时的内存已经花掉了。
    let message = run_err(
        &host,
        "bitflip.table('大表', ['a'], new Array(300000).fill('x').map(v => [v]));",
    );
    assert!(
        message.contains("300000") && message.contains(&MAX_TABLE_CELLS.to_string()),
        "报错要同时给出实际用量与上限：{message}"
    );
}

// ---------------------------------------------------------------------------
// 生命周期：要么全留，要么不留
// ---------------------------------------------------------------------------

#[test]
fn a_failed_script_leaves_no_table() {
    let host = Host::new(None);
    let message = run_err(
        &host,
        r#"
        bitflip.table('已经建好的表', ['a'], [[1], [2]]);
        throw new Error('之后失败了');
        "#,
    );
    assert!(message.contains("之后失败了"), "应当是那个错误：{message}");
    assert!(
        host.tables().is_empty(),
        "失败脚本留下的表看起来和完整的表没有区别，必须一张都不留：{:?}",
        host.tables()
    );
    assert!(host.table_summaries().is_empty());
}

#[test]
fn a_cancelled_script_leaves_no_table() {
    // 控制台里最常见的危险动作：批处理到一半点"停止"。表与标注一样，
    // 被取消时一张都不许剩 —— 一张建好一半的表与一张完整的表长得一样。
    let engine = ScriptEngine::new(Limits {
        timeout: Duration::from_secs(60),
    })
    .expect("引擎");
    let token = engine.cancel_token();
    let host = Host::new(None);

    let watcher = host.clone();
    let canceller = std::thread::spawn(move || {
        // 等表真的建出来再取消：取消请求在"没有脚本在运行"时会被忽略
        // （那是 CancelToken 的语义），太早发等于这次测试什么都没测。
        for _ in 0..2_000 {
            if !watcher.tables().is_empty() {
                break;
            }
            std::thread::sleep(Duration::from_millis(5));
        }
        token.cancel()
    });

    let error = engine
        .run(
            &host,
            "bitflip.table('半截表', ['a'], [[1]]); while (true) {}",
        )
        .expect_err("应当被取消");
    assert!(
        matches!(error, bitflip_script::ScriptError::Cancelled),
        "应当是取消而不是超时或别的错：{error:?}"
    );
    assert!(
        canceller.join().expect("取消线程"),
        "取消必须真的在脚本运行期间发出（否则这次测试是空跑的）"
    );
    assert!(
        host.tables().is_empty(),
        "被取消的脚本不得留下半截表：{:?}",
        host.tables()
    );
}

#[test]
fn a_rerun_does_not_show_the_previous_runs_tables() {
    let host = Host::new(None);
    run_ok(&host, "bitflip.table('上一次的表', ['a'], [[1]]);");
    assert_eq!(host.tables().len(), 1);

    run_ok(&host, "bitflip.log('这次只打日志');");
    assert!(
        host.tables().is_empty(),
        "重跑必须先清空：否则上一次的表会以本次运行结果的身份出现在界面里：{:?}",
        host.tables()
    );
}
